siwe_server.settings:
  type: config_object
  label: "SIWE Server settings"
  mapping:
    jwt_audience:
      type: string
      label: "JWT Audience"
    cors_enabled:
      type: boolean
      label: "CORS enabled"
    allowed_origins:
      type: sequence
      label: "Allowed origins"
      sequence:
        type: string
        label: "Origin"
