siwe_server.settings:
  type: config_object
  label: "SIWE Server settings"
  mapping:
    allow_drupal_login:
      type: boolean
      label: "Allow Drupal login"
    allowed_domains:
      type: sequence
      label: "Allowed Domains"
      sequence:
        type: string
        label: "Domain"
